server:
  port: 8079

spring:
  datasource:
    url: jdbc:postgresql://localhost:5438/pokedex
    username: pokemon
    password: pokemon

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
